# Generated by Django 6.0.2 on 2026-03-01 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='AggregatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
                ('memory', models.CharField(blank=True, max_length=50, verbose_name='Память')),
            ],
            options={
                'verbose_name': 'Сводный товар',
                'verbose_name_plural': 'Сводные товары',
                'unique_together': {('model', 'color', 'memory')},
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pricelists/%Y/%m/%d/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('status', models.CharField(default='new', max_length=20, verbose_name='Статус')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
                ('memory', models.CharField(blank=True, max_length=50, verbose_name='Память')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pricelist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operators.pricelist')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aggregated_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='operators.aggregatedproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.supplier')),
            ],
            options={
                'verbose_name': 'Цена поставщика',
                'verbose_name_plural': 'Цены поставщиков',
                'unique_together': {('aggregated_product', 'supplier')},
            },
        ),
    ]
