# Generated by Django 6.0.2 on 2026-03-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aggregatedproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aggregatedproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='aggregatedproduct',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='aggregatedproduct',
            name='sim_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='SIM'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='product',
            name='sim_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='SIM'),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatedproduct',
            unique_together={('brand', 'model', 'color', 'memory', 'region', 'sim_type')},
        ),
    ]
