# Generated by Django 6.0.2 on 2026-03-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_alter_aggregatedproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pricelists/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
