# Generated by Django 6.0.2 on 2026-03-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_alter_pricelist_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aggregatedproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aggregatedproduct',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='aggregatedproduct',
            name='specs',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристики'),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatedproduct',
            unique_together={('category', 'brand', 'model', 'color', 'memory', 'region', 'sim_type', 'specs')},
        ),
    ]
