# Generated by Django 6.0.2 on 2026-04-21 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0008_operatorprice_source_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('language_code', models.CharField(blank=True, max_length=20, verbose_name='Язык')),
                ('state', models.CharField(blank=True, choices=[('', 'Нет активного сценария'), ('awaiting_request_text', 'Ожидает текст обращения')], default='', max_length=64, verbose_name='Состояние')),
                ('pending_request_type', models.CharField(blank=True, max_length=32, verbose_name='Ожидаемый тип обращения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Telegram клиент',
                'verbose_name_plural': 'Telegram клиенты',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramCustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('price', 'Уточнение цены'), ('availability', 'Уточнение наличия'), ('order', 'Заказ'), ('question', 'Вопрос')], max_length=32, verbose_name='Тип обращения')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Закрыта'), ('cancelled', 'Отменена')], default='new', max_length=32, verbose_name='Статус')),
                ('product_query', models.CharField(blank=True, max_length=255, verbose_name='Запрос по товару')),
                ('client_message', models.TextField(verbose_name='Сообщение клиента')),
                ('operator_note', models.TextField(blank=True, verbose_name='Заметка оператора')),
                ('operator_reply', models.TextField(blank=True, verbose_name='Ответ клиенту')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID сообщения Telegram')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Ответ отправлен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_customer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='operators.telegramcustomer', verbose_name='Клиент')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_requests', to='operators.aggregatedproduct', verbose_name='Товар')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_requests', to='operators.telegrampublication', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Запрос клиента из Telegram',
                'verbose_name_plural': 'Запросы клиентов из Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
