# Generated by Django 6.0.2 on 2026-04-21 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0009_telegramcustomer_telegramcustomerrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramCustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Клиент'), ('operator', 'Оператор')], max_length=20, verbose_name='Отправитель')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID сообщения Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_messages', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='operators.telegramcustomerrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Сообщение в заявке Telegram',
                'verbose_name_plural': 'Сообщения в заявках Telegram',
                'ordering': ['created_at'],
            },
        ),
    ]
