# Generated by Django 6.0.2 on 2026-04-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0010_telegramcustomermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramcustomerrequest',
            name='has_unread_customer_message',
            field=models.BooleanField(default=True, verbose_name='Есть непрочитанное сообщение клиента'),
        ),
    ]
