# Generated by Django 6.0.2 on 2026-04-21 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0011_telegramcustomerrequest_has_unread_customer_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChatCleanupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Telegram chat ID')),
                ('message_ids', models.JSONField(blank=True, default=list, verbose_name='ID сообщений для удаления')),
                ('due_at', models.DateTimeField(verbose_name='Удалить после')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
                ('failed_attempts', models.PositiveIntegerField(default=0, verbose_name='Ошибок обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_tasks', to='operators.telegramcustomer', verbose_name='Клиент')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_tasks', to='operators.telegramcustomerrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Очередь очистки Telegram-чата',
                'verbose_name_plural': 'Очередь очистки Telegram-чатов',
                'ordering': ['due_at'],
            },
        ),
    ]
